filelist: /workspace/AlterDub/module3_dataset/metadata/vocoder_filelist.txt
sample_rate: 16000
hop_length: 80
n_mels: 80

segment_mel_frames: 128
batch_size: 16
num_workers: 4
# Ultra-stable learning rate
lr: 0.00005
betas: [0.8, 0.99]
weight_decay: 0.0

max_steps: 200000
log_every: 50
save_every: 250
checkpoint_dir: /workspace/AlterDub/module5_1_vocoder/checkpoints
run_name: vocoder_v1_hifigan_melloss_db10_ultrasafe

# Loss weights
lambda_fm: 10.0
lambda_mel: 10.0

# STFT/Mel (LOCKED to Module-2)
n_fft: 512
win_length: 160
f0min: 0.0
f0max: 8000.0

use_amp: false
